datadir: /Thema11/Ra/data/

classifiers:
  mitchodira: r4-c7_mithochondria.tif
  nucleus: r4-c7_nucleus.tif

train_data: Tile_r4-c7_Acquisition Spec 3_452994970.tif

dataset_dir: /Thema11/Ipy/results_refactor_all/
results_dir: /Thema11/Ipy/results_refactor_all/

segment:
  r4: Tile_r4-c7_Acquisition Spec 3_452994970.tif
  r5: Tile_r4-c4_Acquisition Spec 3_452994970.tif
  r5_matched: Tile_r4-c4_Acquisition Spec 3_452994970_matched.tif

gaussian_layers: 4
window_size:
  !!python/tuple [3,3]

algorithms:
  - SGD
  - MultinomialNB
  - ZeroR