configfile: "config/config.yaml"


include: "rules/train_model.smk"
include: "rules/graph_training.smk"
include: "rules/predict.smk"

rule all:
    input:
        accuracy=config["graph_accuracy"],
        loss=config["graph_loss"],
        save_location= config["classified_image"],
