configfile: "config/config.yaml"


rule train_model:
    input:
        data_location = config["input_data"]
    output:
        config["model_export"] + "trained_model.h5"

    params:
        early_stopping = config["early_stopping"]

    script:
        "scripts/train_model.py"

rule all:
    input:
        config["model_export"] + "trained_model.h5"